# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build And Push APIs Docker Image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'

env:
  IMAGE_NAME: morooi/morooi-telegram-bot
  VERSION: 1.0.0
  JAR_FILE: morooi-telegram-bot.jar

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Jar
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.JAR_FILE }}
          path: target/${{ env.JAR_FILE }}

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest --build-arg JAR_FILE=${{ env.JAR_FILE }} .

      - name: Push Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker push ${{ env.IMAGE_NAME }}:latest
